### ISSUE TITLE
Stackstorm lesson fails on napalm.get_facts action

### ISSUE THREAD

**Issue by olberger** [nre-learning/nrelabs-curriculum#280]
Stage 2 "actions" of the "Event-Driven Network Automation with StackStorm" lesson fails when issueing st2 run napalm.get_facts hostname=vqfx1
```
st2 run napalm.get_facts hostname=vqfx1
.
id: 5ded55a052364c00cb42dea5
status: failed
parameters:
   hostname: vqfx1
result:   
exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 325, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 183, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 236, in _get_action_instance
    raise exc_cls(msg)
ImportError: Failed to load action class from file "/opt/stackstorm/packs/napalm/actions/get_facts.py" (action file most likely doesn't exist or contains invalid syntax): No module named copyable_regex_object
```

Hth,

**Comment by Mierdin** [comment]
I swear we've already fixed this like twice - probably some kind of deployment problem. Will add it to next curriculum release plan so it at least gets looked at.

**Comment by Mierdin** [comment]
Well, I finally had a chance to look at this and I'm getting an even more severe-looking message:

```
antidote@st2:~$ st2 run napalm.get_facts hostname=vqfx1
.
id: 5e2b9a4352364c00ce461781
status: failed
parameters: 
  hostname: vqfx1
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 325, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 183, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 236, in _get_action_instance
    raise exc_cls(msg)
SyntaxError: Failed to load action class from file "/opt/stackstorm/packs/napalm/actions/get_facts.py" (action file most likely doesn't exist or contains invalid syntax): invalid syntax (cisco_base_connection.py, line 143)

Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 229, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py", line 168, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/opt/stackstorm/packs/napalm/actions/get_facts.py", line 1, in <module>
    from lib.action import NapalmBaseAction
  File "/opt/stackstorm/packs/napalm/actions/lib/action.py", line 4, in <module>
    from napalm import get_network_driver
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/__init__.py", line 3, in <module>
    from napalm.base import get_network_driver
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/__init__.py", line 27, in <module>
    from napalm.base.base import NetworkDriver
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/base.py", line 21, in <module>
    from netmiko import ConnectHandler, NetMikoTimeoutException
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax
```

Fortunately, this points pretty conclusively to the fact that there's a Python 2/3 problem. We should definitely get the StackStorm image up to Py3, but in the meantime, downgrading netmiko to 2.4.2 (last version to support py2) fixes this issue. I'll do some more extensive testing and open a PR to close this.

**Comment by Mierdin** [comment]
Actually, you can instruct stackstorm to provision a python3 virtualenv for a pack with the `--python3` flag, so I tried that, but it looks like python 3.5 is what gets installed, and this syntax needs 3.6+. So in #293 I'll stick with the current approach of pinning an old version of netmiko, that way we can get a fix to this in quickly, and we'll address upgrading the image to 3.6+ and the most recent version of stackstorm in the next release of the curriculum.
